# Generated by Django 4.0.6 on 2022-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание товара')),
                ('categories', models.CharField(choices=[('milk', 'Молочные'), ('organic', 'Органические'), ('fast_feed', 'Быстрого приготовления'), ('drinks', 'Напитки'), ('vegetables', 'Овощи'), ('other', 'Разное')], default='other', max_length=100, verbose_name='Категория')),
                ('balance', models.PositiveIntegerField(verbose_name='Остаток товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, max_length=100, verbose_name='Цена товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'market',
            },
        ),
    ]
